### ISSUE TITLE
1.21?

### ISSUE THREAD

**Issue by meowinqq** [daWinzig/entity-separator#2]
i hate to be that person and i don't mean to bother! just inquiring about whether this mod will receive an update for 1.21 compatibility :') thank you for your time!

**Comment by daWinzig** [comment]
There is the 1.21 version on Modrinth, Curse and GitHub for almost an month already or did I mess something up?

**Comment by meowinqq** [comment]
ack, my bad!! modrinth hadn't featured the 1.21 version and i misremembered having looked at the "all versions" tab -- my apologies!! thank you again for your time
